name: wireguard_dart
description: Wireguard Dart SDK
version: 0.4.2
homepage: https://github.com/mysteriumnetwork/wireguard_dart
repository: https://github.com/mysteriumnetwork/wireguard_dart

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: network.mysterium.wireguard_dart
        pluginClass: WireguardDartPlugin
      ios:
        pluginClass: WireguardDartPlugin
      linux:
        pluginClass: WireguardDartPlugin
      macos:
        pluginClass: WireguardDartPlugin
      windows:
        pluginClass: WireguardDartPluginCApi
